export const people = [
  {
    id: 'advait-sarkar',
    name: 'Advait Sarkar',
    title: 'Affiliated Lecturer at University of Cambridge',
    bio: 'Advait is an affiliated lecturer at the University of Cambridge, honorary lecturer at University College London, and researcher at Microsoft. He studies how to design human interfaces for artificial intelligence, and how to help people program and interact with data.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/AdvaitSarkar.webp',
  },
  {
    id: 'shelley-vohr',
    name: 'Shelley Vohr',
    title: 'Principal Engineer at Microsoft',
    bio: 'Shelley Vohr (she/her) is a software engineer based in Berlin, Germany. She\'s Principal Engineer at Microsoft, where she has worked as an Electron maintainer for over 6 years, as well as on Node.js as a TSC member and collaborator. Outside of work, Shelley loves to uncover hidden treasures at the flea market, eat the saltiest licorice humans can handle, and never misses the daily NYT crossword.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/Shelley_Vohr.webp',
  },
  {
    id: 'cyd-stumpel',
    name: 'Cyd Stumpel',
    title: 'Freelance Creative Developer',
    bio: 'Cyd is a freelance creative developer and part time teacher at the Amsterdam University of Applied Sciences. She creates accessible, award winning websites for everyone; from large organisations like WeTransfer and Amnesty International to creative agencies and freelancers. She\'s got an eye for details and loves to turn flat designs into rich experiences. Cyd has mostly focused on JavaScript animation over the last couple of years but has rediscovered her passion for CSS this year, rebuilding her portfolio with View Transitions and Scroll Driven Animation.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/Cyd.webp',
  },
  {
    id: 'candi-williams',
    name: 'Candi Williams',
    title: 'UX Content Design Director',
    bio: 'By day, Candi\'s a UX content director who loves helping her team thrive, solving complex user experience challenges, and championing inclusive design. With over a decade in experience design - spanning products from banking to dating - she knows a thing or two about IA, AI, and everything in between. By night, she\'s a published author of four books, a tarot reader, and trained sommelier (who tends not to combine them all at once). A self-confessed "word nerd" with a first-class degree in Linguistics, she\'s super passionate about the power of language and the impact it has on what people think, feel, and do (on and offline).',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/CandiWilliams.webp',
  },
  {
    id: 'piccia-neri',
    name: 'Piccia Neri',
    title: 'Accessible Design Trainer & Consultant',
    bio: 'Piccia Neri is on a mission to prove that inclusive design doesn\'t kill creativity: it fuels it. As a UX and accessible design consultant, she leads global projects for companies of all sizes and trains designers, marketers and developers to put accessibility at the heart of their work. Piccia speaks at conferences worldwide, and her current main focus is on balancing creativity and accessibility, without sacrificing either.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/PicciaNeri.webp',
  },
  {
    id: 'alessandra-canella',
    name: 'Alessandra Canella',
    title: 'Design Leader & Mentor',
    bio: 'Alessandra is a design leader with 10+ years shaping product and service design across startups, scale-ups, and the public sector. Formerly Head of Design at Cazoo, MyTutor, and TPXImpact, she\'s known for translating business goals into clear direction for Tech and Design teams to drive growth, retention, and efficiency. Founder of Mega Mentor and Service Design-in\', she brings a collaborative, pragmatic, and user-centred approach to every challenge.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/AlessandraCanella.webp',
  },
  {
    id: 'steve-upton',
    name: 'Steve Upton',
    title: 'Principal Consultant at Thoughtworks',
    bio: 'Steve is a Principal Quality Analyst at Thoughtworks who works to build empowered teams, capable of delivering and taking ownership of quality. He has worked on a wide variety of products, from mainframes to microservices and has a particular interest in complex socio-technical systems and how we work with them. He is passionate about complexity theory, building quality into culture and testing as part of continuous delivery in modern, distributed architectures. Outside of work, Steve enjoys travel and mountains.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/SteveUpton.webp',
  },
  {
    id: 'luke-hay',
    name: 'Luke Hay',
    title: 'Senior User Researcher at Clearleft',
    bio: 'Luke is the senior user researcher at Clearleft. He has 20+ years of experience working with clients to run user research. From kids to pensioners, dress-makers to body-builders, Luke has run research with participants from very different backgrounds. Over the past ten years, Luke has trained hundreds of people in getting reliable insight from their user research.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/LukeHay.webp',
  },
  {
    id: 'soumaya-erradi',
    name: 'Soumaya Erradi',
    title: 'Senior Software Developer @ Atlantis',
    bio: '',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/SoumayaErradi.webp',
  },
  {
    id: 'orcdev',
    name: 'Orcdev',
    title: 'Software Engineer',
    bio: '15 years in the code mines. I build, I break, I conquer - all in orcish style. 🛠️🔥',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/OrcDev.webp',
  },
  {
    id: 'raff-di-meo',
    name: 'Raff Di Meo',
    title: 'Senior Principal UX Designer at Blue Yonder',
    bio: '',
    media: 'https://pub-8541e0f02cf24b9e8fb55faea3ace142.r2.dev/Speakers_www24/RaffFondoGris.webp',
  },
  {
    id: 'guillaume-vaslin',
    name: 'Guillaume Vaslin',
    title: 'Founder & Head of Design at ENNOstudio',
    bio: 'Guillaume is a French designer based in Berlin. Early in his career, he founded Eelusion, a game studio behind some of Europe\'s first augmented reality games. He later served as Managing Director at The European Magazine, where he led the creative direction until its acquisition by Weimar Media Group. He also participated in STARTUP Chile, launching two social ventures while working with prêt-à-porter brands across Latin America. Today, as the founder of ENNOstudio, Guillaume sees design as the bridge between technology and human needs. He focuses on making digital products more inclusive and accessible, collaborating with startups, enterprises, and universities across Europe.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/GuillaumeVaslin.webp',
  },
  {
    id: 'ignacio-chicharro',
    name: 'Ignacio Chicharro',
    title: 'Development Technical Lead at Medida',
    bio: 'Ignacio is a Development Technical Lead with over 8 years of industry experience. He is dedicated to creating full-stack software systems with a special focus on performance and optimization. Outside work he is a passionate Sim Racing and gaming enthusiast.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/IgnacioChicharro.webp',
  },
  {
    id: 'xenia-melikhova',
    name: 'Xenia Melikhova',
    title: 'Frontend developer at TradingView',
    bio: 'Xenia is a frontend developer at TradingView, focused on complex user interfaces: editors, charts, and UI architecture. Interested in performance, scalability, and making complex things feel simple.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/%D0%9A%D1%81%D0%B5%D0%BD%D0%B8%D1%8F%D0%9C%D0%B5%D0%BB%D0%B8%D1%85%D0%BE%D0%B2%D0%B0.webp',
  },
  {
    id: 'jenil-gogari',
    name: 'Jenil Gogari',
    title: 'Senior Product Designer at Datadog',
    bio: 'Jenil Gogari is a Senior Product Designer at Datadog where he leads design tooling and works on the design system DRUIDS by Datadog. Previously, Jenil worked as a UX designer at BookMyShow, India\'s largest entertainment ticketing platform. In the past, he made free website themes, a CSS framework, an icon delivery service and a Chrome extension. Jenil spends his time building tools and products that empower designers and developers to enhance the user experience.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/JenilGogari.webp',
  },
  {
    id: 'dima-malyshenko',
    name: 'Dima Malyshenko',
    title: 'Tech Entrepreneur, CTO, and Software Engineer',
    bio: 'Ukrainian entrepreneur, product strategist, and software engineer with 20+ years of experience. Now based in Berlin after stints in Kyiv and Moscow. Co-founder and former CTO of countX, a B2B fintech that went from first commit to exit in under four years; led product and engineering and built a high-velocity, autonomous team. Influenced by Marty Cagan and Teresa Torres, they champion outcome-driven, cross-functional teams and continuous deployment to deliver measurable impact. Currently pursuing an Executive MBA at London Business School focused on fintech and venture strategy.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/DimaMalyshenko.webp',
  },
  {
    id: 'tamas-kokeny',
    name: 'Tamas Kokeny',
    title: 'Educator at Productkind',
    bio: 'Tamas is an enthusiastic software engineer with a background in product development, technical leadership, and education. He is an Educator at productkind, where he\'s currently building LittleParrot.app, a science-based microlearning platform for busy product people. He also teaches and creates educational content. As a serial entrepreneur, Tamas co-founded multiple ventures, including Bobcats Coding, a digital product studio. His career journey includes technical roles at companies such as Datadog, Cazoo, and Cloudera, where he spearheaded initiatives in software architecture design and led development teams. Beyond his technical contributions, Tamas is deeply committed to fostering talent and sharing knowledge. He served as the Head of Education and Co-Founder at Green Fox Academy, a programming bootcamp in Central Europe, where he managed international mentor teams, created educational content, and designed curricula.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/TamasKokeny.webp',
  },
  {
    id: 'kinga-magyar',
    name: 'Kinga Magyar',
    title: 'Product Builder & Coach at Productkind',
    bio: 'Kinga is a curious product leader and founder of the education company productkind. She is currently building LittleParrot.app, a science-based microlearning platform for busy product people. Through her newsletter, she shares practical, hands-on advice to help product people grow their skills and mindset.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/KingaMagyar.webp',
  },
  {
    id: 'salma-alam-naylor',
    name: 'Salma Alam-Naylor',
    title: 'Head of Developer Education at Nordcraft',
    bio: 'Salma writes code for your entertainment. She helps developers build cool stuff by writing blog posts, making videos, coding live on the internet, and publishing open source projects. After a career as a music teacher and comedian, Salma transitioned to technology in 2014, working as a front end developer and tech lead for startups, agencies and global e-commerce, moving to Developer Experience and Developer Education in 2021. She currently works for Nordcraft as Head of Developer Education. Active in the developer community, Salma is a GitHub Star, a former Microsoft MVP for Developer Technologies (2021-2025), winner of the Jamstack Conf Community Creator Award 2021, and a partnered Twitch streamer. She also makes videos on YouTube about tech and the history of The Internet.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/SalmaAlam-Naylor.png',
  },
  {
    id: 'andreas-moller',
    name: 'Andreas Møller',
    title: 'CEO and Co-Founder of Nordcraft',
    bio: 'Andreas spent 20 years building websites and apps before he finally started Nordcraft and built the design tool he always wanted.',
    media: 'https://pub-feb1369114e049dd80d0cf4ffe55d40e.r2.dev/speakers/AndreasMoller.webp',
  }
]
